-- =====================================================
-- RESTAURANT MANAGEMENT SYSTEM - SUPABASE SCHEMA
-- =====================================================
-- This schema includes:
-- 1. Tables with proper relationships
-- 2. Row Level Security (RLS) policies
-- 3. Indexes for performance
-- 4. Triggers for automation
-- 5. Initial seed data
-- =====================================================

-- =====================================================
-- 1. EXTENSIONS
-- =====================================================
create extension if not exists "uuid-ossp";

-- =====================================================
-- 2. ENUMS
-- =====================================================

-- User roles
create type user_role as enum ('admin', 'customer', 'delivery', 'waiter', 'chef');

-- Order status
create type order_status as enum (
  'placed', 
  'preparing', 
  'cooking', 
  'prepared', 
  'out_for_delivery', 
  'delivered', 
  'cancelled'
);

-- Table status
create type table_status as enum ('available', 'occupied', 'reserved');

-- Booking status
create type booking_status as enum ('pending', 'confirmed', 'cancelled', 'completed');

-- =====================================================
-- 3. TABLES
-- =====================================================

-- -----------------------------------------------------
-- PROFILES TABLE
-- -----------------------------------------------------
create table profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text unique not null,
  full_name text,
  username text unique,
  phone_number text unique,
  role user_role not null default 'customer',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null,
  
  -- Constraints
  constraint username_length check (char_length(username) >= 3),
  constraint phone_format check (phone_number ~ '^[0-9+\-\s()]+$')
);

-- -----------------------------------------------------
-- MENU ITEMS TABLE
-- -----------------------------------------------------
create table menu_items (
  id bigint generated by default as identity primary key,
  name text not null,
  description text,
  price numeric(10,2) not null check (price >= 0),
  category text not null,
  veg boolean not null default true,
  rating numeric(3,2) default 0 check (rating >= 0 and rating <= 5),
  image text default '🍽️',
  is_available boolean not null default true,
  is_special boolean not null default false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- -----------------------------------------------------
-- RESTAURANT TABLES TABLE
-- -----------------------------------------------------
create table restaurant_tables (
  id uuid default gen_random_uuid() primary key,
  table_number integer not null unique,
  capacity integer not null check (capacity > 0),
  status table_status not null default 'available',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- -----------------------------------------------------
-- ORDERS TABLE
-- -----------------------------------------------------
create table orders (
  id uuid default gen_random_uuid() primary key,
  user_id uuid references profiles(id) on delete set null,
  table_id uuid references restaurant_tables(id) on delete set null,
  status order_status not null default 'placed',
  total_amount numeric(10,2) not null check (total_amount >= 0),
  delivery_person_id uuid references profiles(id) on delete set null,
  delivery_address text,
  is_paid boolean not null default false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null,
  
  -- Check constraints
  constraint valid_delivery check (
    (status in ('out_for_delivery', 'delivered') and delivery_person_id is not null) or
    (status not in ('out_for_delivery', 'delivered'))
  )
);

-- -----------------------------------------------------
-- ORDER ITEMS TABLE
-- -----------------------------------------------------
create table order_items (
  id uuid default gen_random_uuid() primary key,
  order_id uuid references orders(id) on delete cascade not null,
  menu_item_id bigint references menu_items(id) on delete restrict not null,
  name text not null,
  quantity integer not null check (quantity > 0),
  price numeric(10,2) not null check (price >= 0),
  image text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- -----------------------------------------------------
-- TABLE BOOKINGS TABLE
-- -----------------------------------------------------
create table table_bookings (
  id uuid default gen_random_uuid() primary key,
  user_id uuid references profiles(id) on delete cascade not null,
  table_id uuid references restaurant_tables(id) on delete set null,
  booking_date date not null,
  booking_time time not null,
  guests_count integer not null check (guests_count > 0),
  status booking_status not null default 'pending',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null,
  
  -- Check business hours (11 AM to 10 PM)
  constraint business_hours check (
    booking_time >= time '11:00:00' and 
    booking_time <= time '22:00:00'
  )
);

-- -----------------------------------------------------
-- OFFERS TABLE
-- -----------------------------------------------------
create table offers (
  id uuid default gen_random_uuid() primary key,
  title text not null,
  description text,
  discount_code text unique not null,
  discount_percentage numeric(5,2) default 0,
  is_active boolean not null default true,
  valid_from timestamp with time zone default timezone('utc'::text, now()),
  valid_until timestamp with time zone,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- -----------------------------------------------------
-- ADDRESSES TABLE (for customer saved addresses)
-- -----------------------------------------------------
create table addresses (
  id uuid default gen_random_uuid() primary key,
  user_id uuid references profiles(id) on delete cascade not null,
  address_label text not null, -- e.g., "Home", "Work"
  address_line1 text not null,
  address_line2 text,
  city text not null,
  state text not null,
  pincode text not null,
  phone_number text not null,
  is_default boolean not null default false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- -----------------------------------------------------
-- FAVORITES TABLE (menu item wishlist)
-- -----------------------------------------------------
create table favorites (
  id uuid default gen_random_uuid() primary key,
  user_id uuid references profiles(id) on delete cascade not null,
  menu_item_id bigint references menu_items(id) on delete cascade not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  
  -- Unique constraint to prevent duplicate favorites
  unique(user_id, menu_item_id)
);

-- -----------------------------------------------------
-- NOTIFICATIONS TABLE
-- -----------------------------------------------------
create table notifications (
  id uuid default gen_random_uuid() primary key,
  user_id uuid references profiles(id) on delete cascade not null,
  title text not null,
  message text not null,
  type text not null, -- 'order', 'booking', 'promotion', 'system'
  is_read boolean not null default false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- -----------------------------------------------------
-- SUPPORT_TICKETS TABLE (Help & Support)
-- -----------------------------------------------------
create table support_tickets (
  id uuid default gen_random_uuid() primary key,
  user_id uuid references profiles(id) on delete cascade not null,
  subject text not null,
  description text not null,
  status text not null default 'open', -- 'open', 'in_progress', 'resolved', 'closed'
  priority text default 'normal', -- 'low', 'normal', 'high', 'urgent'
  admin_response text,
  resolved_at timestamp with time zone,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- =====================================================
-- 4. INDEXES FOR PERFORMANCE
-- =====================================================

-- Profiles
create index idx_profiles_email on profiles(email);
create index idx_profiles_username on profiles(username);
create index idx_profiles_phone on profiles(phone_number);
create index idx_profiles_role on profiles(role);

-- Menu items
create index idx_menu_items_category on menu_items(category);
create index idx_menu_items_available on menu_items(is_available);
create index idx_menu_items_special on menu_items(is_special);
create index idx_menu_items_rating on menu_items(rating desc);

-- Orders
create index idx_orders_user_id on orders(user_id);
create index idx_orders_table_id on orders(table_id);
create index idx_orders_status on orders(status);
create index idx_orders_delivery_person on orders(delivery_person_id);
create index idx_orders_created_at on orders(created_at desc);
create index idx_orders_is_paid on orders(is_paid);
create index idx_orders_status_created on orders(status, created_at desc);

-- Order items
create index idx_order_items_order_id on order_items(order_id);
create index idx_order_items_menu_item_id on order_items(menu_item_id);

-- Restaurant tables
create index idx_restaurant_tables_status on restaurant_tables(status);
create index idx_restaurant_tables_number on restaurant_tables(table_number);

-- Table bookings
create index idx_table_bookings_user_id on table_bookings(user_id);
create index idx_table_bookings_table_id on table_bookings(table_id);
create index idx_table_bookings_date on table_bookings(booking_date);
create index idx_table_bookings_status on table_bookings(status);
create index idx_table_bookings_date_time on table_bookings(booking_date, booking_time);

-- Offers
create index idx_offers_active on offers(is_active);
create index idx_offers_validity on offers(valid_from, valid_until);

-- Addresses
create index idx_addresses_user_id on addresses(user_id);
create index idx_addresses_default on addresses(user_id, is_default);

-- Favorites
create index idx_favorites_user_id on favorites(user_id);
create index idx_favorites_menu_item on favorites(menu_item_id);

-- Notifications
create index idx_notifications_user_id on notifications(user_id);
create index idx_notifications_read on notifications(user_id, is_read);
create index idx_notifications_created on notifications(created_at desc);

-- Support tickets
create index idx_support_tickets_user_id on support_tickets(user_id);
create index idx_support_tickets_status on support_tickets(status);

-- =====================================================
-- 5. TRIGGERS FOR UPDATED_AT
-- =====================================================

-- Function to update updated_at timestamp
create or replace function update_updated_at_column()
returns trigger as $$
begin
  new.updated_at = timezone('utc'::text, now());
  return new;
end;
$$ language plpgsql;

-- Apply trigger to all tables with updated_at
create trigger update_profiles_updated_at before update on profiles
  for each row execute function update_updated_at_column();

create trigger update_menu_items_updated_at before update on menu_items
  for each row execute function update_updated_at_column();

create trigger update_restaurant_tables_updated_at before update on restaurant_tables
  for each row execute function update_updated_at_column();

create trigger update_orders_updated_at before update on orders
  for each row execute function update_updated_at_column();

create trigger update_table_bookings_updated_at before update on table_bookings
  for each row execute function update_updated_at_column();

create trigger update_addresses_updated_at before update on addresses
  for each row execute function update_updated_at_column();

create trigger update_support_tickets_updated_at before update on support_tickets
  for each row execute function update_updated_at_column();

-- =====================================================
-- 6. ROW LEVEL SECURITY (RLS) POLICIES
-- =====================================================

-- Enable RLS on all tables
alter table profiles enable row level security;
alter table menu_items enable row level security;
alter table restaurant_tables enable row level security;
alter table orders enable row level security;
alter table order_items enable row level security;
alter table table_bookings enable row level security;
alter table offers enable row level security;
alter table addresses enable row level security;
alter table favorites enable row level security;
alter table notifications enable row level security;
alter table support_tickets enable row level security;

-- -----------------------------------------------------
-- PROFILES POLICIES
-- -----------------------------------------------------
-- Users can view their own profile
create policy "Users can view own profile"
  on profiles for select
  using (auth.uid() = id);

-- Users can view other users' profiles (for role-based features)
create policy "Users can view other profiles"
  on profiles for select
  using (true);

-- Users can insert their own profile (during signup)
create policy "Users can insert own profile"
  on profiles for insert
  with check (auth.uid() = id);

-- Users can update their own profile
create policy "Users can update own profile"
  on profiles for update
  using (auth.uid() = id);

-- Admins can update any profile (for role management)
create policy "Admins can update any profile"
  on profiles for update
  using (
    exists (
      select 1 from profiles
      where id = auth.uid() and role = 'admin'
    )
  );

-- Admins can view all profiles
create policy "Admins can view all profiles"
  on profiles for select
  using (
    exists (
      select 1 from profiles
      where id = auth.uid() and role = 'admin'
    )
  );

-- -----------------------------------------------------
-- MENU ITEMS POLICIES
-- -----------------------------------------------------
-- Anyone can view available menu items
create policy "Anyone can view menu items"
  on menu_items for select
  using (true);

-- Only admins can modify menu items
create policy "Admins can insert menu items"
  on menu_items for insert
  with check (
    exists (
      select 1 from profiles
      where id = auth.uid() and role = 'admin'
    )
  );

create policy "Admins can update menu items"
  on menu_items for update
  using (
    exists (
      select 1 from profiles
      where id = auth.uid() and role = 'admin'
    )
  );

create policy "Admins can delete menu items"
  on menu_items for delete
  using (
    exists (
      select 1 from profiles
      where id = auth.uid() and role = 'admin'
    )
  );

-- -----------------------------------------------------
-- RESTAURANT TABLES POLICIES
-- -----------------------------------------------------
-- Anyone can view tables
create policy "Anyone can view restaurant tables"
  on restaurant_tables for select
  using (true);

-- Only admins can modify tables
create policy "Admins can insert tables"
  on restaurant_tables for insert
  with check (
    exists (
      select 1 from profiles
      where id = auth.uid() and role = 'admin'
    )
  );

create policy "Admins can update tables"
  on restaurant_tables for update
  using (
    exists (
      select 1 from profiles
      where id = auth.uid() and role = 'admin'
    )
  );

-- Waiters can update table status
create policy "Waiters can update table status"
  on restaurant_tables for update
  using (
    exists (
      select 1 from profiles
      where id = auth.uid() and role = 'waiter'
    )
  );

-- -----------------------------------------------------
-- ORDERS POLICIES
-- -----------------------------------------------------
-- Users can view their own orders
create policy "Users can view own orders"
  on orders for select
  using (
    auth.uid() = user_id or
    auth.uid() = delivery_person_id or
    exists (
      select 1 from profiles
      where id = auth.uid() and role in ('admin', 'chef', 'waiter')
    )
  );

-- Customers can create their own orders
create policy "Users can create orders"
  on orders for insert
  with check (auth.uid() = user_id);

-- Update policies based on role
create policy "Users can update own orders"
  on orders for update
  using (
    (auth.uid() = user_id and status in ('placed', 'cancelled')) or
    auth.uid() = delivery_person_id or
    exists (
      select 1 from profiles
      where id = auth.uid() and role in ('admin', 'chef', 'waiter')
    )
  );

-- -----------------------------------------------------
-- ORDER ITEMS POLICIES
-- -----------------------------------------------------
-- View order items if you can view the order
create policy "Users can view order items"
  on order_items for select
  using (
    exists (
      select 1 from orders
      where id = order_items.order_id and (
        auth.uid() = user_id or
        auth.uid() = delivery_person_id or
        exists (
          select 1 from profiles
          where id = auth.uid() and role in ('admin', 'chef', 'waiter')
        )
      )
    )
  );

-- Insert order items (when creating order)
create policy "Users can insert order items"
  on order_items for insert
  with check (
    exists (
      select 1 from orders
      where id = order_items.order_id and auth.uid() = user_id
    )
  );

-- -----------------------------------------------------
-- TABLE BOOKINGS POLICIES
-- -----------------------------------------------------
-- Users can view their own bookings
create policy "Users can view own bookings"
  on table_bookings for select
  using (auth.uid() = user_id);

-- Users can create bookings
create policy "Users can create bookings"
  on table_bookings for insert
  with check (auth.uid() = user_id);

-- Users can cancel their pending bookings
create policy "Users can update own bookings"
  on table_bookings for update
  using (
    auth.uid() = user_id and 
    status in ('pending', 'confirmed')
  );

-- Admins/Waiters can update any booking
create policy "Staff can update bookings"
  on table_bookings for update
  using (
    exists (
      select 1 from profiles
      where id = auth.uid() and role in ('admin', 'waiter')
    )
  );

-- -----------------------------------------------------
-- OFFERS POLICIES
-- -----------------------------------------------------
-- Anyone can view active offers
create policy "Anyone can view active offers"
  on offers for select
  using (is_active = true);

-- Only admins can modify offers
create policy "Admins can manage offers"
  on offers for all
  using (
    exists (
      select 1 from profiles
      where id = auth.uid() and role = 'admin'
    )
  );

-- -----------------------------------------------------
-- ADDRESSES POLICIES
-- -----------------------------------------------------
-- Users can view their own addresses
create policy "Users can view own addresses"
  on addresses for select
  using (auth.uid() = user_id);

-- Users can manage their own addresses
create policy "Users can manage own addresses"
  on addresses for all
  using (auth.uid() = user_id);

-- -----------------------------------------------------
-- FAVORITES POLICIES
-- -----------------------------------------------------
-- Users can view their own favorites
create policy "Users can view own favorites"
  on favorites for select
  using (auth.uid() = user_id);

-- Users can manage their own favorites
create policy "Users can manage own favorites"
  on favorites for all
  using (auth.uid() = user_id);

-- -----------------------------------------------------
-- NOTIFICATIONS POLICIES
-- -----------------------------------------------------
-- Users can view their own notifications
create policy "Users can view own notifications"
  on notifications for select
  using (auth.uid() = user_id);

-- Users can update their own notifications (mark as read)
create policy "Users can update own notifications"
  on notifications for update
  using (auth.uid() = user_id);

-- System/Admins can create notifications
create policy "Admins can create notifications"
  on notifications for insert
  with check (true); -- Can be restricted further if needed

-- -----------------------------------------------------
-- SUPPORT TICKETS POLICIES
-- -----------------------------------------------------
-- Users can view their own tickets
create policy "Users can view own tickets"
  on support_tickets for select
  using (auth.uid() = user_id);

-- Users can create tickets
create policy "Users can create tickets"
  on support_tickets for insert
  with check (auth.uid() = user_id);

-- Users can update their own tickets
create policy "Users can update own tickets"
  on support_tickets for update
  using (auth.uid() = user_id);

-- Admins can view and update all tickets
create policy "Admins can manage all tickets"
  on support_tickets for all
  using (
    exists (
      select 1 from profiles
      where id = auth.uid() and role = 'admin'
    )
  );

-- =====================================================
-- 7. FUNCTIONS
-- =====================================================

-- Function to get orders with items
create or replace function get_order_with_items(p_order_id uuid)
returns json as $$
declare
  v_order json;
begin
  select row_to_json(o.*) into v_order
  from (
    select 
      o.*,
      array_agg(oi.*) as order_items,
      p.full_name as customer_name,
      p.phone_number as customer_phone
    from orders o
    left join order_items oi on oi.order_id = o.id
    left join profiles p on p.id = o.user_id
    where o.id = p_order_id
    group by o.id, p.full_name, p.phone_number
  ) o;
  
  return v_order;
end;
$$ language plpgsql;

-- Function to get daily revenue
create or replace function get_daily_revenue(p_date date)
returns numeric as $$
declare
  v_revenue numeric;
begin
  select coalesce(sum(total_amount), 0) into v_revenue
  from orders
  where date(created_at) = p_date
    and is_paid = true
    and status != 'cancelled';
  
  return v_revenue;
end;
$$ language plpgsql;

-- Function to create notification
create or replace function create_notification(
  p_user_id uuid,
  p_title text,
  p_message text,
  p_type text
) returns void as $$
begin
  insert into notifications (user_id, title, message, type)
  values (p_user_id, p_title, p_message, p_type);
end;
$$ language plpgsql;

-- =====================================================
-- 8. SEED DATA
-- =====================================================

-- Insert sample menu items
insert into menu_items (name, description, price, category, veg, rating, image, is_available, is_special) values
('Paneer Butter Masala', 'Rich and creamy tomato-based curry with paneer', 349, 'Main Course', true, 4.8, '🍛', true, true),
('Chicken Biryani', 'Aromatic basmati rice with spiced chicken', 399, 'Biryani', false, 4.9, '🍚', true, true),
('Garlic Naan', 'Freshly baked naan with garlic butter', 89, 'Breads', true, 4.6, '🫓', true, false),
('Caesar Salad', 'Crisp romaine lettuce with Caesar dressing', 249, 'Starters', true, 4.3, '🥗', true, false),
('Gulab Jamun', 'Sweet dumplings in sugar syrup', 149, 'Desserts', true, 4.7, '🍨', true, false),
('Mango Lassi', 'Refreshing yogurt drink with mango', 129, 'Beverages', true, 4.5, '🥤', true, false),
('Tandoori Chicken', 'Chicken marinated in yogurt and spices', 449, 'Main Course', false, 4.8, '🍗', true, true),
('Dal Makhani', 'Black lentils slow-cooked overnight', 299, 'Main Course', true, 4.7, '🍲', true, false),
('Veg Momos', 'Steamed dumplings filled with vegetables', 199, 'Starters', true, 4.4, '🥟', true, false),
('Chocolate Brownie', 'Warm brownie with vanilla ice cream', 229, 'Desserts', true, 4.6, '🍰', true, false);

-- Insert sample restaurant tables
insert into restaurant_tables (table_number, capacity, status) values
(1, 2, 'available'),
(2, 2, 'available'),
(3, 4, 'available'),
(4, 4, 'available'),
(5, 4, 'available'),
(6, 6, 'available'),
(7, 6, 'available'),
(8, 8, 'available'),
(9, 2, 'available'),
(10, 4, 'available');

-- Insert sample offers
insert into offers (title, description, discount_code, discount_percentage, is_active, valid_until) values
('Welcome Offer', 'Get 30% off on your first 3 orders', 'WELCOME30', 30.00, true, timezone('utc'::text, now()) + interval '30 days'),
('Weekend Special', 'Flat 20% off on weekends', 'WEEKEND20', 20.00, true, timezone('utc'::text, now()) + interval '7 days'),
('Free Delivery', 'Free delivery on orders above ₹500', 'FREEDEL', 0.00, true, null);

-- =====================================================
-- 9. COMMENTS FOR DOCUMENTATION
-- =====================================================

comment on table profiles is 'User profiles with role-based access control';
comment on table menu_items is 'Restaurant menu items with categories and pricing';
comment on table restaurant_tables is 'Physical tables in the restaurant';
comment on table orders is 'Customer orders with status tracking';
comment on table order_items is 'Individual items within an order';
comment on table table_bookings is 'Table reservations by customers';
comment on table offers is 'Promotional offers and discount codes';
comment on table addresses is 'Saved delivery addresses for users';
comment on table favorites is 'User favorite menu items (wishlist)';
comment on table notifications is 'Push notifications for users';
comment on table support_tickets is 'Customer support requests';

-- =====================================================
-- END OF SCHEMA
-- =====================================================

-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.addresses (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  address_label text NOT NULL,
  address_line1 text NOT NULL,
  address_line2 text,
  city text NOT NULL,
  state text NOT NULL,
  pincode text NOT NULL,
  phone_number text NOT NULL,
  is_default boolean NOT NULL DEFAULT false,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT addresses_pkey PRIMARY KEY (id),
  CONSTRAINT addresses_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.customer_otps (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  email text NOT NULL,
  otp_code text NOT NULL,
  expires_at timestamp with time zone NOT NULL,
  used boolean DEFAULT false,
  used_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT customer_otps_pkey PRIMARY KEY (id)
);
CREATE TABLE public.delivery_addresses (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  label text NOT NULL,
  address_line1 text NOT NULL,
  address_line2 text,
  city text NOT NULL,
  state text NOT NULL,
  pincode text NOT NULL,
  latitude numeric,
  longitude numeric,
  is_default boolean DEFAULT false,
  is_within_delivery_zone boolean DEFAULT true,
  distance_from_restaurant numeric,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT delivery_addresses_pkey PRIMARY KEY (id),
  CONSTRAINT delivery_addresses_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.delivery_config (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  config_key text NOT NULL UNIQUE,
  config_value jsonb NOT NULL,
  description text,
  updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()),
  CONSTRAINT delivery_config_pkey PRIMARY KEY (id)
);
CREATE TABLE public.delivery_person_locations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  delivery_person_id uuid,
  latitude numeric NOT NULL,
  longitude numeric NOT NULL,
  accuracy numeric,
  speed numeric,
  bearing numeric,
  recorded_at timestamp with time zone DEFAULT timezone('utc'::text, now()),
  CONSTRAINT delivery_person_locations_pkey PRIMARY KEY (id),
  CONSTRAINT delivery_person_locations_delivery_person_id_fkey FOREIGN KEY (delivery_person_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.delivery_personnel (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  profile_id uuid NOT NULL UNIQUE,
  is_available boolean DEFAULT true,
  is_on_duty boolean DEFAULT false,
  current_order_id uuid,
  rating numeric DEFAULT 5.00,
  total_deliveries integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()),
  CONSTRAINT delivery_personnel_pkey PRIMARY KEY (id),
  CONSTRAINT delivery_personnel_profile_id_fkey FOREIGN KEY (profile_id) REFERENCES public.profiles(id),
  CONSTRAINT delivery_personnel_current_order_id_fkey FOREIGN KEY (current_order_id) REFERENCES public.orders(id)
);
CREATE TABLE public.delivery_zones (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  pincode text NOT NULL UNIQUE,
  city text NOT NULL,
  state text NOT NULL,
  is_active boolean DEFAULT true,
  max_distance_km numeric DEFAULT 20,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()),
  CONSTRAINT delivery_zones_pkey PRIMARY KEY (id)
);
CREATE TABLE public.dine_in_sessions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  table_id uuid NOT NULL,
  user_id uuid NOT NULL,
  session_status text DEFAULT 'active'::text CHECK (session_status = ANY (ARRAY['active'::text, 'completed'::text, 'cancelled'::text])),
  payment_status text DEFAULT 'pending'::text CHECK (payment_status = ANY (ARRAY['pending'::text, 'paid'::text, 'partial'::text])),
  payment_method text CHECK (payment_method = ANY (ARRAY['cod'::text, 'upi'::text, 'razorpay'::text])),
  total_amount numeric DEFAULT 0,
  paid_amount numeric DEFAULT 0,
  started_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  completed_at timestamp with time zone,
  payment_completed_at timestamp with time zone,
  notes text,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  session_name text,
  CONSTRAINT dine_in_sessions_pkey PRIMARY KEY (id),
  CONSTRAINT dine_in_sessions_table_id_fkey FOREIGN KEY (table_id) REFERENCES public.restaurant_tables(id),
  CONSTRAINT dine_in_sessions_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.favorites (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  menu_item_id bigint NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT favorites_pkey PRIMARY KEY (id),
  CONSTRAINT favorites_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT favorites_menu_item_id_fkey FOREIGN KEY (menu_item_id) REFERENCES public.menu_items(id)
);
CREATE TABLE public.menu_items (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  name text NOT NULL,
  price numeric NOT NULL,
  category text NOT NULL,
  veg boolean DEFAULT true,
  rating numeric DEFAULT 4.5,
  image text NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  is_available boolean DEFAULT true,
  is_special boolean DEFAULT false,
  CONSTRAINT menu_items_pkey PRIMARY KEY (id)
);
CREATE TABLE public.notifications (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  title text NOT NULL,
  message text NOT NULL,
  type text NOT NULL,
  is_read boolean NOT NULL DEFAULT false,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT notifications_pkey PRIMARY KEY (id),
  CONSTRAINT notifications_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.offers (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  title text NOT NULL,
  description text NOT NULL,
  discount_code text NOT NULL,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT offers_pkey PRIMARY KEY (id)
);
CREATE TABLE public.order_items (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  order_id uuid,
  menu_item_id bigint,
  name text NOT NULL,
  quantity integer NOT NULL,
  price numeric NOT NULL,
  image text,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  special_instructions text,
  spice_level text DEFAULT 'medium'::text CHECK (spice_level = ANY (ARRAY['mild'::text, 'medium'::text, 'spicy'::text, 'extra_spicy'::text])),
  CONSTRAINT order_items_pkey PRIMARY KEY (id),
  CONSTRAINT order_items_order_id_fkey FOREIGN KEY (order_id) REFERENCES public.orders(id),
  CONSTRAINT order_items_menu_item_id_fkey FOREIGN KEY (menu_item_id) REFERENCES public.menu_items(id)
);
CREATE TABLE public.orders (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  table_id uuid,
  status text DEFAULT 'placed'::text CHECK (status = ANY (ARRAY['placed'::text, 'preparing'::text, 'cooking'::text, 'prepared'::text, 'served'::text, 'out_for_delivery'::text, 'delivered'::text, 'cancelled'::text])),
  total_amount numeric DEFAULT 0,
  delivery_person_id uuid,
  delivery_address text,
  is_paid boolean DEFAULT false,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  order_type text CHECK (order_type = ANY (ARRAY['dine_in'::text, 'delivery'::text])),
  placed_by text CHECK (placed_by = ANY (ARRAY['customer'::text, 'waiter'::text])),
  customer_name text,
  customer_email text,
  customer_phone text,
  delivery_address_line2 text,
  delivery_pincode text,
  delivery_latitude numeric,
  delivery_longitude numeric,
  delivery_instructions text,
  payment_method text CHECK (payment_method = ANY (ARRAY['cod'::text, 'upi'::text, 'razorpay'::text, 'cash'::text])),
  payment_status text DEFAULT 'pending'::text CHECK (payment_status = ANY (ARRAY['pending'::text, 'paid'::text, 'failed'::text, 'refunded'::text])),
  payment_id text,
  paid_at timestamp with time zone,
  delivery_status text DEFAULT 'pending'::text,
  assigned_at timestamp with time zone,
  picked_up_at timestamp with time zone,
  delivered_at timestamp with time zone,
  estimated_delivery_time timestamp with time zone,
  actual_delivery_time timestamp with time zone,
  distance_to_customer numeric,
  route_polyline text,
  razorpay_order_id text,
  razorpay_signature text,
  delivery_rating integer CHECK (delivery_rating >= 1 AND delivery_rating <= 5),
  delivery_feedback text,
  updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()),
  notes text,
  session_name text,
  session_id uuid,
  CONSTRAINT orders_pkey PRIMARY KEY (id),
  CONSTRAINT orders_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT orders_table_id_fkey FOREIGN KEY (table_id) REFERENCES public.restaurant_tables(id),
  CONSTRAINT orders_delivery_person_id_fkey FOREIGN KEY (delivery_person_id) REFERENCES auth.users(id),
  CONSTRAINT orders_session_id_fkey FOREIGN KEY (session_id) REFERENCES public.dine_in_sessions(id)
);
CREATE TABLE public.otp_verifications (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  email text NOT NULL,
  otp_code text NOT NULL,
  purpose text NOT NULL DEFAULT 'email_verification'::text,
  expires_at timestamp with time zone NOT NULL,
  used boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT otp_verifications_pkey PRIMARY KEY (id)
);
CREATE TABLE public.profiles (
  id uuid NOT NULL,
  full_name text,
  email text,
  role text DEFAULT 'customer'::text CHECK (role = ANY (ARRAY['admin'::text, 'customer'::text, 'delivery'::text, 'waiter'::text, 'chef'::text])),
  username text UNIQUE,
  phone_number text,
  current_latitude numeric,
  current_longitude numeric,
  last_location_update timestamp with time zone,
  total_deliveries integer DEFAULT 0,
  rating numeric DEFAULT 5.00,
  CONSTRAINT profiles_pkey PRIMARY KEY (id),
  CONSTRAINT profiles_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id)
);
CREATE TABLE public.restaurant_tables (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  table_number integer NOT NULL UNIQUE,
  capacity integer NOT NULL,
  status text DEFAULT 'available'::text CHECK (status = ANY (ARRAY['available'::text, 'occupied'::text, 'reserved'::text])),
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  occupied_at timestamp with time zone,
  occupied_by_customer_name text,
  occupied_by_customer_email text,
  current_order_id uuid,
  is_reserved boolean DEFAULT false,
  reservation_start_time time without time zone,
  reservation_end_time time without time zone,
  auto_release_at timestamp with time zone,
  CONSTRAINT restaurant_tables_pkey PRIMARY KEY (id),
  CONSTRAINT restaurant_tables_current_order_id_fkey FOREIGN KEY (current_order_id) REFERENCES public.orders(id)
);
CREATE TABLE public.support_tickets (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  subject text NOT NULL,
  description text NOT NULL,
  status text NOT NULL DEFAULT 'open'::text,
  priority text DEFAULT 'normal'::text,
  admin_response text,
  resolved_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT support_tickets_pkey PRIMARY KEY (id),
  CONSTRAINT support_tickets_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.table_bookings (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid,
  table_id uuid,
  booking_date date NOT NULL,
  booking_time time without time zone NOT NULL,
  guests_count integer NOT NULL,
  status text DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'confirmed'::text, 'cancelled'::text, 'completed'::text])),
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  special_requests text,
  phone_number text,
  occasion text,
  customer_name text,
  customer_email text,
  booking_duration integer DEFAULT 90,
  CONSTRAINT table_bookings_pkey PRIMARY KEY (id),
  CONSTRAINT table_bookings_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT table_bookings_table_id_fkey FOREIGN KEY (table_id) REFERENCES public.restaurant_tables(id)
);
CREATE TABLE public.table_sessions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  table_id uuid,
  customer_name text,
  customer_email text,
  customer_phone text,
  started_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  ended_at timestamp with time zone,
  total_orders integer DEFAULT 0,
  total_amount numeric DEFAULT 0,
  payment_status text DEFAULT 'pending'::text CHECK (payment_status = ANY (ARRAY['pending'::text, 'paid'::text, 'pending_partial'::text, 'completed'::text])),
  status text DEFAULT 'active'::text CHECK (status = ANY (ARRAY['active'::text, 'completed'::text])),
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT table_sessions_pkey PRIMARY KEY (id),
  CONSTRAINT table_sessions_table_id_fkey FOREIGN KEY (table_id) REFERENCES public.restaurant_tables(id)
);
CREATE TABLE public.upi_payments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  order_id uuid NOT NULL,
  vpa text NOT NULL DEFAULT 'anshjpokar@oksbi'::text,
  amount numeric NOT NULL DEFAULT 0,
  upi_link text NOT NULL,
  transaction_id text,
  beneficiary_name text,
  status text NOT NULL DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'verification_requested'::text, 'verified'::text, 'failed'::text, 'expired'::text])),
  qr_expires_at timestamp with time zone NOT NULL,
  verified_at timestamp with time zone,
  verified_by uuid,
  verification_notes text,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT upi_payments_pkey PRIMARY KEY (id),
  CONSTRAINT upi_payments_verified_by_fkey FOREIGN KEY (verified_by) REFERENCES public.profiles(id)
);